preserve_hierarchy: true
source_language: en

files:
  - source: /docs/content/**/*.{md,mdx}
    translation: /docs/site/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/%original_path%/%original_file_name%
    ignore:
      - /docs/content/**/*.excalidraw
      - /docs/content/**/*.png
      - /docs/content/**/*.jpg
      - /docs/content/**/*.jpeg
      - /docs/content/**/*.gif
      - /docs/content/**/*.svg

  - source: /docs/site/i18n/en/**/*.json
    translation: /docs/site/i18n/%two_letters_code%/%original_path%/%original_file_name%

languages_mapping:
  two_letters_code:
    ko: ko